{% set name = "chemprop" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemprop-{{ version }}.tar.gz
  sha256: a7783fa75f719b1ab52812d1a032a85bc75ddd238cb12daefb48516adf764900

build:
  noarch: python
  entry_points:
    - chemprop=chemprop.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <3.13,>=3.11
    - pip
  run:
    - python <3.13,>=3.11
    - pytorch::pytorch >=2.1
    - astartes
    - aimsim
    - configargparse
    - lightning >=2.0
    - numpy <2.0
    - pandas
    - rdkit
    - scikit-learn
    - scipy

test:
  imports:
    - chemprop
  commands:
    - chemprop train --help
    - chemprop predict --help
    - chemprop hpopt --help
  requires:
    - pip

about:
  home: https://github.com/chemprop/chemprop
  summary: Molecular Property Prediction with Message Passing Neural Networks
  dev_url: https://github.com/chemprop/chemprop
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JacksonBurns
    - jan-janssen
